@extends('layouts_backend.app')



@section('contents')



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{asset('blogtemplate/css/detail.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css" integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Ga+Maamli&display=swap" rel="stylesheet"> 
    <title>Document</title>
</head>
<body>
   <div class="container">
    <section class="img-g">
        
        <img src="{{asset($player->foto2)}}" alt="" class="img8x">
        <div class="overlay"></div>

        <figure class="content">
            <div class="img88x">
                <img src="{{asset($player->fotoprofile)}}" alt="">
            </div>
            <h2>{{$player -> no_punggung}}</h2>
            <div class="profile">
                <h1>{{$player -> nama_depan}}</h1>
                <h3>{{$player -> nama_belakang}}</h3>
                <div class="border"></div>
                <img src="{{asset($player->foto1)}}" alt="" srcset="">
                <p>Born :{{$player -> tanggal_lahir}}</p>
            </div>
        <figure>

    </section>
    <section class="info">
        <h2>{{$player -> nama_depan}}{{$player -> belakang}}</h2>
        <div class="border"></div>
        <h4>Player Profile</h4>
        <div class="border"></div>
    </section>
        <section class="paragraf1">
            <p>{{$player -> Desck1}}</p>
            <p>{{$player -> Desck2}}</p>
        </section>
<section class="slide-container">
        <div class="slider">
            <div class="slides">
                <div class="slide"><img src="{{asset($player->foto2)}}" alt="Image 1"></div>
                <div class="slide"><img src="{{asset($player->foto3)}}" alt="Image 2"></div>
                <div class="slide"><img src="{{asset($player->foto4)}}" alt="Image 3"></div>
                <!-- Add more slides as needed -->
            </div>
            <button class="prev" onclick="prevSlide()">&#10094;</button>
            <button class="next" onclick="nextSlide()">&#10095;</button>
            <div class="dots">
                <!-- Dots will be dynamically generated by JavaScript -->
            </div>
        </div>
    </section>
    <section class="paragraf2">
        <p>{{$player -> Desck3}}</p>
        <p>{{$player -> Desck4}}</p>
    </section>
    
   <script>
    // script.js
let currentSlide = 0;

function showSlide(index) {
    const slides = document.querySelector('.slides');
    const dots = document.querySelectorAll('.dot');
    const totalSlides = document.querySelectorAll('.slide').length;
    
    if (index >= totalSlides) {
        currentSlide = 0;
    } else if (index < 0) {
        currentSlide = totalSlides - 1;
    } else {
        currentSlide = index;
    }

    slides.style.transform = `translateX(-${currentSlide * 100}%)`;

    // Update dots
    dots.forEach(dot => dot.classList.remove('active'));
    dots[currentSlide].classList.add('active');
}

function nextSlide() {
    showSlide(currentSlide + 1);
}

function prevSlide() {
    showSlide(currentSlide - 1);
}

function createDots() {
    const dotsContainer = document.querySelector('.dots');
    const totalSlides = document.querySelectorAll('.slide').length;

    for (let i = 0; i < totalSlides; i++) {
        const dot = document.createElement('span');
        dot.className = 'dot';
        dot.addEventListener('click', () => showSlide(i));
        dotsContainer.appendChild(dot);
    }
    
    // Set the first dot as active
    if (totalSlides > 0) {
        document.querySelectorAll('.dot')[0].classList.add('active');
    }
}

// Initialize slider
// Change slide every 5 seconds

   </script>
</body>
</html>
@endsection